### ISSUE TITLE
What is the format of SRC_EMBEDDINGS.TXT?

### ISSUE THREAD

**Issue by lucas-acc** [artetxem/vecmap#12]
I tried the embedding output with GloVe, where the format of embedding is a word a line, each line is a word followed by a comma, and its embeddings are separated by spaces. However this format doesn't work.

When I run:`python3 vecmap/normalize_embeddings.py unit center -i make_embedding/cn_vectors.txt -o SRC_EMBEDDINGS.NORMALIZED.TXT`

The error is:
`Traceback (most recent call last):
  File "vecmap/normalize_embeddings.py", line 52, in <module>
    main()
  File "vecmap/normalize_embeddings.py", line 33, in main
    words, matrix = embeddings.read(f)
  File "/home/wuhaixu/desktop/beat_cross_embedding/vecmap/embeddings.py", line 23, in read
    count = int(header[0]) if threshold <= 0 else min(threshold, int(header[0]))
ValueError: invalid literal for int() with base 10: '，'`

**Comment by artetxem** [comment]
The embeddings should be in word2vec text format, so you should remove the commas and add a header with the size of the embeddings.

**Comment by lucas-acc** [comment]
Thank you very much! So would it be ok using gensim make the embeddings?

**Comment by artetxem** [comment]
Not sure about the format used by gensim but I guess so. These are simple text files anyway, so it should be straightforward to convert from one format to another.

**Comment by lucas-acc** [comment]
Just add the number of words and dimension of embedding word to the head of the embedding.txt, then it works. Thank you again.
