### ISSUE TITLE
Re-weighting difference between ACL2018 paper and code

### ISSUE THREAD

**Issue by zhangxiangnick** [artetxem/vecmap#13]
Really enjoyed your ACL2018 paper! Need some clarification for the re-weighting step.

In your ACL2018 paper, it says re-weighting is used as "a final step once self-learning has converged to a good solution."

In the code ([line 314](https://github.com/artetxem/vecmap/blob/master/map_embeddings.py#L314)), it seems like re-weighting is used in every step of self-learning.

Does it make much difference how re-weighting is used?

**Comment by artetxem** [comment]
Re-weighting is only applied in the last iteration as described in the paper: when the variable 'end' is False (which happens in all iterations but the last one) we learn an orthogonal mapping (line 282).
