### ISSUE TITLE
Do we need the initial word embeddings sorted by word frequency? 

### ISSUE THREAD

**Issue by zhangxiangnick** [artetxem/vecmap#14]
In updating the src/tgt word similarity matrix, it seems like only the first **vocabulary_cutoff** rows of the embedding matrix are used ([code](https://github.com/artetxem/vecmap/blob/master/map_embeddings.py#L342)), instead of over all words.

Similarly, in getting unsupervised initial dictionary, only the first **unsupervised_vocab** rows of the embedding matrix are used. ([code](https://github.com/artetxem/vecmap/blob/master/map_embeddings.py#L175)), instead of over all words.

In your ACL2018 paper, you suggested frequency based vocab cutoff. So does it mean the initial word embeddings need to be sorted by word frequency (popular words come first)?

**Comment by artetxem** [comment]
Yes, the input embeddings need to be sorted by frequency. As far as I know, most software to train embeddings do that though (at least word2vec, glove and fasttext).
