### ISSUE TITLE
Mapping multiple languages into the same space

### ISSUE THREAD

**Issue by ccsasuke** [artetxem/vecmap#17]
Hi,

I'm trying to obtain some unsupervised multilingual embeddings by individually map each of the other languages into English. However, it seems by default there are some reweighting/whitening/normalization happening on both of the source and target languages.

Could you point me a way to set up the arguments so the target embedding stays unchanged that I end up with a multilingual space?

Thank you.

**Comment by artetxem** [comment]
Adding the --orthogonal flag should do what you want.
