### ISSUE TITLE
How to evaluate on other dataset and language

### ISSUE THREAD

**Issue by zhixuzhichang** [artetxem/vecmap#19]
I ran the code on the dataset, 1.8M Chinese and English monolingual data respectively. My command is "python3 map_embeddings.py --unsupervised SRC.EMB TRG.EMB SRC_MAPPED.EMB TRG_MAPPED.EMB". Finally, I got "Coverage: 64.67%  Accuracy: 53.61%" on the test set , https://s3.amazonaws.com/arrival/dictionaries/en-zh.5000-6500.txt, which contains 2230 word pairs.
 It is normal?

**Comment by artetxem** [comment]
Coverage seems a bit low, but accuracy is reasonable. I have never used that dataset so can't tell you more.
