### ISSUE TITLE
Regarding Multilingual Word Embedding and its Citation

### ISSUE THREAD

**Issue by twadada** [artetxem/vecmap#21]
I tried mapping word embeddings of more than two languages into the same space using your models (acl2018 or aai18). However, since these models apply whitening, normalization and reweighting to the source and target sides, it does not seem to be possible to map them into a common space.

In #17 ,  you have mentioned that adding the "--orthogonal" flag should keep the target embeddings unchanged. Is it compatible with the "--acl2018" or "--aaai2018" options? If not, which unsupervised/supervised method is allowed to be used with the orthogonal option and which paper to cite?

**Comment by artetxem** [comment]
If you dig into the code, you will see that --acl2018 or --aaai2018 simply set some defaults that can be overwritten by the rest of the arguments in the command line, so it is possible to use the --orthogonal flag together with either of them. However, that is not exactly what our proposed method from ACL18 and AAAI18 do, so please clarify that in your paper in case you cite them.

Alternatively, you can try the --emnlp2016 and --acl2017 options without the --orthogonal flag (these options learn an orthogonal mapping by default). The results should be similar to --aaai2018 and --acl2018 with --orthogonal, respectively, and you could cite those papers directly.

**Comment by twadada** [comment]
Thank you for your quick reply. So I understand that the difference between "--acl2017" and "--acl2018 --orthogonal"  is the dictionary induction step, and the process of learning a mapping is the same (the Procrustes problem) -- is that right?

**Comment by artetxem** [comment]
Sorry, now that I think about it, '--acl2018 --orthogonal' should work better than '--acl2017' because the internal dictionary induction step changes (and is better for the former) as you mention. '--emnlp2016' and '--aaai2018 --orthogonal' should indeed be similar.

The mapping that is iteratively learned through self-learning is always orthogonal (learned through Procrustes), even for ACL18, but the final one is not.

**Comment by twadada** [comment]
Oh, I didn't notice that self-learning always works with the orthogonal method. Thank you for clarifying that.

Is that right that '--emnlp2016' and '--aaai2018 --orthogonal'  will work in the same way? In your AAAI paper, you mention that orthogonal methods without any whitening, re-weighting and de-whitening correspond to the solution of Artetxe, Labaka, and Agirre (2016).

**Comment by artetxem** [comment]
Yes, that's correct.
