### ISSUE TITLE
Please clarify about mapped embeddings

### ISSUE THREAD

**Issue by aburkov** [artetxem/vecmap#4]
I would just clarify the meaning of SRC_EMBEDDINGS.MAPPED.TXT and TRG_EMBEDDINGS.MAPPED.TXT.

Let say I train my monolingual embeddings for French and separately monolingual embeddings for English.

Now I want to have one set of embeddings, that I can use to represent both French and English words in my machine learning tasks. Should I use SRC_EMBEDDINGS.MAPPED.TXT or TRG_EMBEDDINGS.MAPPED.TXT? Or any of them?

**Comment by artetxem** [comment]
You should use both together: SRC_EMBEDDINGS.MAPPED.TXT for the source language words and TRG_EMBEDDINGS.MAPPED.TXT for the target language words. Note that, even if they are in different files, these mapped embeddings represent words in a shared space, so they are compatible between them (unlike the original embeddings).

If you don't like having separate files for the source and the target language, you can always merge them into a single file taking care of collisions (e.g. taking the average of words that are in both vocabularies).

**Comment by aburkov** [comment]
Thank you! If I independently have embeddings for English and embeddings for French, then I want to project both into a shared space, is there any difference which of the two languages I should pick as source and which one as target?

**Comment by artetxem** [comment]
When using standard mapping both options are exactly equivalent. This is not true for the self-learning extension, but the differences should be small. In other words, either option should be fine.

**Comment by aburkov** [comment]
Cool. What if I do both ways, and then average vectors of two shared spaces, would it give "better" vectors?

**Comment by artetxem** [comment]
I wouldn't expect that to bring any significant improvement, but you can try it and see what happens.

**Comment by PVinay737** [comment]
@artetxem I have a clarification

-  How should one use the `SRC_MAPPED.EMB` and `TRG_MAPPED.EMB` in a NMT system where the initial embeddings  are `SRC.EMB`(fastText) and `TRG.EMB`(fastText)

Is it by concatenating the two files or by replacing them correspondingly ?

**Comment by PVinay737** [comment]
@artetxem I need a clarification

-  How should one use the `SRC_MAPPED.EMB` and `TRG_MAPPED.EMB` in a NMT system where the initial embeddings  are `SRC.EMB`(fastText) and `TRG.EMB`(fastText)

Is it by concatenating the two files or by replacing them correspondingly ?
