### ISSUE TITLE
I can't download the data, why?

### ISSUE THREAD

**Issue by shizhediao** [artetxem/vecmap#7]
When I type ./get_data.sh
It get stucked and have no progress
I don't change the code

<img width="707" alt="12345" src="https://user-images.githubusercontent.com/18120087/32151746-65e58550-bced-11e7-9fc5-d04519efaebf.png">

**Comment by artetxem** [comment]
Just tested it and it is working well for me. Note that the script does not show any progress, and it will take some time to run depending on your connection (up to an hour might be reasonable). So please wait for a longer time and let me know if the problem persists.
