### ISSUE TITLE
Questions about the output during training progress.

### ISSUE THREAD

**Issue by yudianer** [artetxem/vecmap#9]
Hi, excuse me please. What do the below outputs mean during the training progress?

ITERATION 14 (165.40s)
	- Objective:          28.3509%
ITERATION 15 (166.71s)
	- Objective:          28.5072%

**Comment by artetxem** [comment]
It should be self-explanatory. It's the iteration number, how long the iteration took, and the value of the objective function at that iteration. Our ACL paper describes the objective function we use and what each iteration does exactly. If you are not familiar with these concepts, I would recommend you to first learn about the basics of machine learning.
